<a href="https://colab.research.google.com/github/FahimS45/Geometry/blob/master/Self_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 2
b = 4
c = a+b
print(c)

6


In [ ]:
number = int(input("Please enter you number: "))
print("You number: ",number)

Please enter you number: 100
You number:  100


In [ ]:
list2 = [each ** 2 for each in range(7)]
print(list2)

[0, 1, 4, 9, 16, 25, 36]


In [ ]:
even_list = [each for each in range (1,11) if each % 2 == 0 or each % 3 == 0]
print(even_list)


[2, 3, 4, 6, 8, 9, 10]


In [ ]:
#matrix #array
from numpy import *
m1 = matrix('1,2,3;10,20,30')
print(m1)
print()
m2 = array([[1,2,3],
      [10,20,30]])
print(m2)



[[ 1  2  3]
 [10 20 30]]
[[ 1  2  3]
 [10 20 30]]


In [ ]:
even_list = []
odd_list = []
list = [even_list.append(each) if each%2==0 else odd_list.append(each) for each in range(10)]
print(list)


[None, None, None, None, None, None, None, None, None, None]


In [ ]:
# In general way
from numpy import *
transposed_matrix = []
matrix = array ([[1, 2, 3, 4], [4, 5, 6, 8]])
for i in range(len(matrix[0])):
        transposed_row = []

        for row in matrix:
              transposed_row.append(row[i])
        transposed_matrix.append(transposed_row)
new_matrix = array ([transposed_matrix])
print(new_matrix)


[4 5 6 8]
[[[1 4]
  [2 5]
  [3 6]
  [4 8]]]


In [ ]:
# Finding Transpose of a Matrix using List Comprehension
matrix = [[1, 2], [3,4], [5,6], [7,8]]
transpose_matrix = [[row[i] for row in matrix] for i in range(len(matrix[0]))]
print (transpose_matrix)

[5, 6]
[[1, 3, 5, 7], [2, 4, 6, 8]]


In [ ]:
import ast

code = "print('Hello, world!')"
tree = ast.parse(code)

print(ast.dump(tree))
  

Module(body=[Expr(value=Call(func=Name(id='print', ctx=Load()), args=[Constant(value='Hello, world!')], keywords=[]))], type_ignores=[])


In [ ]:
def count_vowels(string):
    vowels = "aeiouAEIOU"
    count = 0
    for char in string:
        if char in vowels:
            count += 1
    return count

print("Number of Vowels: ",count_vowels(input("Please enter you String: ")))

Please enter you String: Appliano
Number of Vowels:  4


In [ ]:
def check(list):
  new_list = []
  for each in list:
    if each.startswith("a") or each.startswith("A"):
      new_list.append(each)
    else:
      pass
  return new_list
strings = ["Apple", "Kimra", "awesome", "Army", "banana"]
print("Final list: ",check(strings))


Final list:  ['Apple', 'awesome', 'Army']


In [ ]:
class Animal:
    def make_sound(self):
        print("The animal makes a sound.")

class Dog(Animal):
    def make_sound(self):
        print("The dog barks.")

# Create an object of the Dog class
random_animal = Animal()

# Call the make_sound method on the Dog object
random_animal.make_sound() # Output: The dog barks.

The animal makes a sound.


In [ ]:
class Calculator:
    def add(self, x, *y):
        a = x
        for i in y:
          a = a + i
        return a
        
# Create an object of the Calculator class
calc = Calculator()

# Call the add method with two arguments
print(calc.add(1, 2, 4, 5, 6, 8)) # Output: 3

# Call the add method with three arguments
# print(calc.add(1, 2, 3)) # Output: 6

26


In [ ]:
from abc import ABC, abstractmethod

class Shape(ABC):
  @abstractmethod
  def area (self):
    pass
class Triangle(Shape):


(1, 2, 3, 4)


In [ ]:
lst = [1, 2, 3]
lst[0] = 3
print(lst)



[3, 2, 3]


In [ ]:
lst = [1,2,3]
sorted_lst = sorted(lst)
print(lst)
print(len(lst))

[1, 2, 3]
3


In [ ]:
from abc import ABC, abstractmethod

class Geometry_prop(ABC):
    @abstractmethod
    def types(self):
        pass

    @abstractmethod
    def area(self):
        pass

    @abstractmethod
    def angle_sum(self):
        pass

intro_input = input("Welcome to 'GEOMETRY WITH FUN'\nTo learn 3-sided geometry, enter '3'\nTo learn 4-sided geometry, enter '4'\nTo learn Circular geometry, enter '0': ")

if intro_input == '3':
    class Triangles(Geometry_prop):
        def __init__(self, side1, side2):
            self.side1 = side1
            self.side2 = side2

        def types(self):
            print("There are in general three types of triangles. They are as follows:\n1. Equilateral triangle\n2. Isoceles triangle\n3. Isoceles-right triangle")

        def area(self):
            height = (self.side1**2 - self.side2**2)**0.5
            length = self.side2
            return 2 * (0.5 * height * length)

        def angle_sum(self):
            print("The sum of the interior angles of any triangle is always '180 degrees'.")

    seq = ["1st", "2nd", "3rd"]
    tri_sides = []
    for i in seq:
        while True:
            input_len = int(input(f"Please enter the length of {i} side: "))
            if input_len > 0:
                tri_sides.append(input_len)
                sorted_tri_sides = sorted(tri_sides)
                break
            else:
                print("Can't be a value of any real side!\nPlease input a real value.")

    while sorted_tri_sides[2] > sorted_tri_sides[0] + sorted_tri_sides[1] or sorted_tri_sides[2] < sorted_tri_sides[0] - sorted_tri_sides[1]:
        input_len = int(input("ERROR!\nAccording to Triangle's Third rule: 3rd side of any triangle must be less than the sum of the other two sides or greater than the subtraction of the other two sides!\nPlease enter an acceptable value: "))
        sorted_tri_sides[2] = input_len1
        

    if sorted_tri_sides[0] == sorted_tri_sides[1] == sorted_tri_sides[2]:
        tri = Triangles(sorted_tri_sides[0], sorted_tri_sides[1] * 0.5)
        tri.types()
        tri.angle_sum()
        print(f"According to your input, it's an 'Equilateral triangle'.\nAnd the area of such triangle is: {tri.area()}")

    elif sorted_tri_sides[0] == sorted_tri_sides[1]:
        tri = Triangles(sorted_tri_sides[0], sorted_tri_sides[1] * 0.5)
        tri.types()
        tri.angle_sum()
        print(f"According to your input, it's an 'Isoceles/Isoceles-Right triangle'.\nAnd the area of such triangle is: {tri.area()}")

    else:
        tri = Triangles(sorted_tri_sides[0], sorted_tri_sides[1] * 0.5)
        tri.types()
        tri.angle_sum()
        print("According to your input, it's an 'Irregular triangle'.\nAnd the area calculation requires much more complex code!")


Welcome to 'GEOMETRY WITH FUN'
To learn 3-sided geometry, enter '3'
To learn 4-sided geometry, enter '4'
To learn Circular geometry, enter '0': 3
Please enter the length of 1st side: 3
Please enter the length of 2nd side: 4
Please enter the length of 3rd side: 1
There are in general three types of triangles. They are as follows:
1. Equilateral triangle
2. Isoceles triangle
3. Isoceles-right triangle
The sum of the interior angles of any triangle is always '180 degrees'.
According to your input, it's an 'Irregular triangle'.
And the area calculation requires much more complex code!


In [ ]:
from abc import ABC, abstractmethod

class Geometry_prop(ABC):

    @abstractmethod
    def area(self, side1, side2):
        pass
    
class rectang(Geometry_prop):
    def area(self, side1, sode2):
        height = (self.side1**2 - self.side2**2)**0.5
        length = self.side2
        return 2 * (0.5 * height * length)

result = rectang()
print(result.area(5,4))

AttributeError: ignored

In [ ]:
class MyClass:
    def __init__(self):
        self._value = 0

    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, new_value):
        self._value = new_value

output = MyClass()
print(f"User's Value: {output.value}")
check_key = input("If you are the User, please verify yourself using your surname here: ")
if check_key == "Tasin":
    changed_val = int(input("Welcome Mr, Tasin! Please enter the value you want to print: "))
    output.value = changed_val
    print(output.value)
else:
    print("You are not authorized to change.")
    





User's Value: 0
If you are the User, please verify yourself using your surname here: Fahim
You are not authorized to change.


In [ ]:
class Car:
    def __init__(self):
        self.speed = 0  # private attribute

    def accelerate(self, increment):
        self.speed += increment

    def get_speed(self):
        return self.speed


my_car = Car()
my_car.accelerate(20)
print(my_car.speed)
print(my_car.get_speed()) 

20
20


In [ ]:
class MyBaseClass:
    def __init__(self):
        self._protected_data = 30

class MyDerivedClass(MyBaseClass):
    def display_protected_data(self):
        print(self._protected_data)

my_object = MyDerivedClass()
my_object.display_protected_data() 

30


In [ ]:
class MyBaseClass:
    def __init__(self):
        self._protected_data = 30

class MyDerivedClass(MyBaseClass):
    def display_protected_data(self):
        print(self._protected_data)

my_object = MyBaseClass()
my_object.display_protected_data()

AttributeError: ignored

In [63]:
import pandas as pd
import csv

file_path = "Working_CSV_file.csv"

try:
    file = open(file_path, 'w')
    file.close()
    print(f"{file_path} has been created successfully!")
except Exception as e:
    print("Something went wrong while creating!", str(e))

inner_datas = [[1, 2, 3], [10, 20, 30], [100, 200, 300]]

try:
    with open(file_path, 'w') as file:
      csv_writer = csv.writer(file)
      csv_writer.writerows(inner_datas)
    print(f"Writing has been done succefully!")
except Exception as e:
    print("Something went wrong while writing!", str(e))

try:
    with open(file_path, 'r') as file:
      csv_reader = csv.reader(file)
      for rows in csv_reader:
        print(rows)
except Exception as e:
    print("Something went worng while reading!", str(e))

data = pd.read_csv(file_path)
data['4'] = [500, 600]
data['5'] = [700, 800]

drop_data = data.drop(['1'], axis=1)
drop_data.rename(columns = {'2' : "First", '3' : "Second", '4' : "Third", '5' : "Fourth"}, inplace=True)
print(drop_data)





Working_CSV_file.csv has been created successfully!
Writing has been done succefully!
['1', '2', '3']
['10', '20', '30']
['100', '200', '300']
   First  Second  Third  Fourth
0     20      30    500     700
1    200     300    600     800
